version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,s3,iam,vpc,route53
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
